### ISSUE TITLE
Performance issues on integrated graphics

### ISSUE THREAD

**Issue by coderobe** [wacossusca34/glava#10]
On my i7-4710HQ, running glava with the `bars` module, `native` transparency and a size of 1920x300(+) yields surprisingly low FPS, @wacossusca34 says this should really yield 200+

The performance goes up drastically when ran on a dedicated GPU instead of the integrated one on the same device.

**Comment by wacossusca34** [comment]
Finally got around to this, through testing with `llvmpipe` to simulate terrible graphics hardware, I managed to pinpoint two issues:

* Usage of the `texture` function to lookup data from `sampler1D` types was a bad idea on some hardware or drivers. I replaced this with `texelFetch` calls to ensure no interpolation/filtering was occurring in the background. Texture lookups using `smooth_audio` in `smooth.glsl` now use rounding in the shader itself to find a texel to sample from, instead of using `GL_NEAREST` in the underlying texture type.

* `smooth.glsl` was performing on-the-fly smoothing for every fragment. This was incredibly slow on integrated graphics chips or software rendering. I added a `#request setsmoothpass` directive to allow users to enable a special rendering pass that gets the smoothing processing out of the way before any rendering is done, which is accomplished by rendering to a 1D texture (and is set to `true` by default).

There is a consequence to the second fix, where smoothing settings are now set via `setsmoothfactor` instead in `smooth_parameters.glsl` (since the C code needs this value for the extra pass). This will break existing configs using `#define SMOOTH`.

@coderobe please test this on your hardware. It should drastically improve performance (went from ~6FPS @1920x1080 GLava window to 50-60 FPS on `llvmpipe`).

**Comment by Aaahh** [comment]
Well I've used glava with intel graphics 630 before and I knew it was 60 fps, but now it seems way too slow
FPS: 60.45, UPS: 20.81
When I use my 1050ti instead, I get insane frame-rate (depending on settings, with my configuration like 700 fps) but my computer starts heating up. With a frame-limit of 200, things are better but it's still warm for a audio visualizer. I don't have airflow problems, but it is a laptop. I average like 40 Celsius regularly
It could still be my Ubuntu install but I'm not that sure
Even if it weren't, and I use my ti, it consumes too much resources for what it is. I suggest it being adaptive but I'm aware of the challenged associated with that.

**Comment by Aaahh** [comment]
Well I updated my system today and UPS is back up to 60, my bad

**Comment by wacossusca34** [comment]
> Well I've used glava with intel graphics 630 before and I knew it was 60 fps, but now it seems way too slow
FPS: 60.45, UPS: 20.81

@Aaahh that sounds really odd. My first guess is that audio updates are being recieved too slow, or that core usage is maxed out. Although, in the case of core usage, the framerate should be dropping as well.

An easy way to test this would be to see if the CPU usage for a thread/core is at 100%. If so, then there's probably some glaring performance issue that can (probably) be fixed with ease.

Otherwise, two things could be the cause of the problem:

- PulseAudio isn't submitting data fast enough to GLava, and the UPS is dropping as a result of not having enough new data to operate on. This will create much choppier output and signals that occur outside of the window-time used for FFT will not be present in the output, although interpolation will mitigate this a lot.

- The OpenGL driver is doing something weird and rendering code is blocking irregularily. I don't find this likely as the framerate should be also affected by this -- try turning off vsync (`#request setswap 0`) to see if anything changes.

> When I use my 1050ti instead, I get insane frame-rate (depending on settings, with my configuration like 700 fps) but my computer starts heating up. With a frame-limit of 200, things are better but it's still warm for a audio visualizer. I don't have airflow problems, but it is a laptop. I average like 40 Celsius regularly

This will depend on the module you are using. GLava's actual rendering isn't particularily lightweight since all the drawing logic is done in the shaders. It might reduce GPU resource usage to draw the visualizer geometry by actually uploading verticies instead, but this will increase CPU usage and driver overhead, plus is harder to write in such a way that new modules can be easily added.

Heat is also a pretty bad metric to use. Your GPU is obviously going to see usage outside of what normal, non-accelerated applications would use -- and I don't have a lot of control over what the driver is doing behind the scenes. You should, at the very least, have vsync enabled.

**Comment by Aaahh** [comment]
![peek 2018-03-30 02-30](https://user-images.githubusercontent.com/3966556/38217494-9e476dea-369c-11e8-8a57-06827171d1c7.gif)
I know it's low fps but you can kind of make out when the glava frame glitches to a previous one for a split second

**Comment by wacossusca34** [comment]
@Aaahh that's strange. If GLava is reporting that it's running under 60FPS, despite getting hangs like this, then two things could be the cause:

* The OpenGL driver has some sort of bug with enqueuing pre-rendered frames and/or vsync.
* The compositor being used has a bug that is causing windows to appear hung (perhaps this is specific to transparent windows?)

If the hang was caused by my own code, the time it takes to calculate, render, and sync/display the frame would change, causing the reported FPS to drop. Since this isn't the case, it's more likely that the driver or compositor is responsible here since GLava itself isn't experiencing a hang.

**Comment by Aaahh** [comment]
low ups seems to be related to if I let my computer suspend or not (after it lags)

**Comment by wacossusca34** [comment]
@Aaahh I am not remotely surprised by suspend causing issues with existing OpenGL contexts, and definately means the issue is out of my hands (the driver should handle issues that arise with power loss). It's probably specific to your hardware, too.

You're best off writing a rule/script to restart GLava when your system resumes.

**Comment by wacossusca34** [comment]
@Aaahh Oh, so then it's PulseAudio not serving data fast enough to GLava... but only after suspend? Does sound otherwise still work properly after resuming? Perhaps this is a PulseAudio bug you should report.

**Comment by Aaahh** [comment]
Sound works fine
I've found a way to reproduce the glitching
run about 6 glava's, each with a different color. It's then super apparent
I'm guessing it'd take more on the notion of 12 or more for you
So basically either a race condition or an old frame that took long to load is not dropped but rather drawn

**Comment by wacossusca34** [comment]
@Aaahh the fact that it takes multiple GLava instances to cause the problem definately points to some driver-related issue. GLava (obviously) doesn't have any inter-process communication going on so there's no reason to think a race condition would occur with my own code, the only point where it all comes together is the underlying driver handling the OpenGL contexts.

I'm also on the `nvidia` driver so I have no way of verifying this behaviour (and I have no integrated graphics on this system).

**Comment by Aaahh** [comment]
I narrowed it down to a Pulse Audio issue, but moving on from that, when there is not audio being played, perhaps glava shouldn't be redrawing an empty frame?

**Comment by Aaahh** [comment]
I found options to monitor for audio config changes through pulse audio
solving that other bug, also I just realized that i put the loop where I
tear down and build up pulse over and over rather than poll for changes

**Comment by wacossusca34** [comment]
A small note on performance issues, I recently noted that `compton` causes GLava's visuals to appear to be much choppier on the `nvidia` driver. This shouldn't come as a huge surprise, compositors are known to cause issues with performance in other OpenGL applications, and is only noticeable for me on high refresh rates (120/144Hz).

There's some odd interaction going on here, and I wouldn't be surprised if other drivers exhibit similar problems with compositors and GLava.
