### ISSUE TITLE
GLava will not move to second monitor.

### ISSUE THREAD

**Issue by StarrKiss** [wacossusca34/glava#101]
No matter my setgeometry settings, glava will not move to my second monitor ( to the left of my main one). It is very annoying and I have no clue why.    I was using this guide: https://www.linuxuprising.com/2018/11/embed-audio-visualizer-on-your-linux.html

Which says that in order to have it on the left-most monitor, the x and y values should be set to 0. This simply keeps the visualizer on the main monitor. I don't quite get what to do, as the monitor I want it on is 1440 by 900, and my main monitor is 1920 by 1080. I have tried shrinking the width and height (size) of the vizualiser to 1440 by 900, and it just shrinks the visualizer on my main monitor, still not working on my second one. How to fix?

**Comment by wacossusca34** [comment]
> Which says that in order to have it on the left-most monitor, the x and y values should be set to 0

This depends on how you have your screen space configured, but you want to offset your x axis positively to position it to the right, and negatively to the left. _Usually_ the bottom left corner on your leftmost monitor is the origin (`x: 0, y: 0`), but sometimes it has a negative offset (possibly `x: -1440, y: 0` in your case).

So, try this (position GLava on the bottom of your left monitor, 450px high):

```GLSL
#request setgeometry -1440 0 1440 450
```

**Comment by StarrKiss** [comment]
That did not work, it is still stuck on right monitor.

**Comment by StarrKiss** [comment]
In addition, none of the movement controls in set geometry seem to work: If I shrink the size of the thing and try and move it, it does not. I am refreshing it every time.

**Comment by wacossusca34** [comment]
@StarrKiss Are you using KDE? It's possible the window position is being overridden or ignored by the WM. You can try to use `#request setforcegeometry true` as a fix if this is the case. You can also try using unmanaged window types (`#request setxwintype "!-"`) to see if it behaves differently as a last resort.

**Comment by StarrKiss** [comment]
Neitther of those seem to have any effect.

**Comment by StarrKiss** [comment]
I was also wrong about the movement controls, they do work, I just did not see it.

**Comment by StarrKiss** [comment]
Also, It works if you run the command on the second monitor (with the terminal on the second monitor) but this is not ideal for autostart.

**Comment by wacossusca34** [comment]
KDE unfortunately is infamous for not playing well with GLava and has a lot of unusual behavior regarding window positioning and stacking.

To clarify: a (0, 0) positioned window with `setforcegeometry true` enabled places the GLava window on the monitor it was ran from? In that case, it sounds like each monitor is serving a separate desktop.

 Keep in mind if you are trying to use unmanaged windows, you should _not_ be combining it with the `--desktop` flag. If you have separate virtual desktops for each monitor, then this would be your ideal solution since there's no way to pin windows to a _set_ of virtual desktops, only one or all of them.

Alternatively, you could configure KDE to have unified virtual desktops across all monitors.

**Comment by wacossusca34** [comment]
@StarrKiss have you resolved the issue?

**Comment by StarrKiss** [comment]
Instead of booting it on startup, I just create a new terminal on the secondary monitor to start up glava, and it works fine, but is more inconvenient.

**Comment by wacossusca34** [comment]
@StarrKiss this honestly sounds like yet another strange behavior enforced by KWin to use local coordinates for each virtual desktop. The good news is that KWin exposes a _lot_ of options such that you can probably disable this behavior, but I would need to test this to get you a detailed fix.

It would be nice if the default KWin behavour wasn't so hostile to abnormal EWMH window types. I'll close this since this is related to this long-standing issue: #4
