### ISSUE TITLE
Transparent screen on default settings

### ISSUE THREAD

**Issue by gerardparareda** [wacossusca34/glava#104]
Hi,

I've installed Glava through apt in Ubuntu 18.04 LTS. When I run glava with default settings nothing appears on the screen, like this:

![Screenshot from 2019-03-11 20-26-30](https://user-images.githubusercontent.com/4147225/54151946-4f429180-443c-11e9-859f-0c47da739add.png)

It's just transparent. I get this warning on running glava --desktop:
`No presets for current desktop environment ("GNOME Shell"), using default presets for embedding`

I've tried reinstalling and compiling it myself but nothing works. Is it possible it can't find my audio or should it be displaying something already?

Thanks!

**Comment by wacossusca34** [comment]
@gerardparareda

First off, transparency _is_ default for all windows. Most people want transparency, but if you want it disabled you can use `#request setopacity none`.

> It's just transparent. I get this warning on running glava --desktop:
> `No presets for current desktop environment ("GNOME Shell"), using default presets for embedding`

This is not an issue (nor a warning), it just means it's going to use options from `env_default.glsl` for desktop mode. GNOME does not need any workarounds, so the default `#request setxwintype "desktop"` works fine.

> Is it possible it can't find my audio or should it be displaying something already?

This is the likely issue here, since GLava's rendering loop is functioning (according to stdout). I need some the output of `pactl list sources` and `pactl list source-outputs` to figure out what is causing this.

Also, if you have a microphone, you can set `#request setsource <id>` to the source number associated with it in `pactl list sources`. Whether or not GLava visualizes microphone input should help narrow down the issue further.

Likely what is happening is your default output device found by GLava is not _actually_ your default device, or hardware monitors are not working due to a driver bug (or simply due to the lack of hardware support, but pulseaudio _should_ be able to work around this).

**Comment by wacossusca34** [comment]
I just noticed your framerates are all over the place, so there could actually be a rendering/update bug. That means this:

> Additionally, try glava -m "radial". If you see a black circle, that rules out any rendering bugs.

Needs to be done to rule out such issues, along with the output of `glxinfo | grep OpenGL` and `uname -r`.

Could just be a side effect from broken audio input, though, since that will effect your framerate (and also cause interpolation to auto-enable if updates drop).

**Comment by gerardparareda** [comment]
Thanks a lot for the feedback and sorry for my ignorance. Let's see:
I do see a back circle with `glava -m "radial"`. It doesn't move when music is playing, but it's there, over the transparent background, as expected.

The output of `glxinfo | grep OpenGL` is:
<pre><font color="#EF2929"><b>OpenGL</b></font> vendor string: NVIDIA Corporation
<font color="#EF2929"><b>OpenGL</b></font> renderer string: GeForce GTX 950M/PCIe/SSE2
<font color="#EF2929"><b>OpenGL</b></font> core profile version string: 4.6.0 NVIDIA 410.78
<font color="#EF2929"><b>OpenGL</b></font> core profile shading language version string: 4.60 NVIDIA
<font color="#EF2929"><b>OpenGL</b></font> core profile context flags: (none)
<font color="#EF2929"><b>OpenGL</b></font> core profile profile mask: core profile
<font color="#EF2929"><b>OpenGL</b></font> core profile extensions:
<font color="#EF2929"><b>OpenGL</b></font> version string: 4.6.0 NVIDIA 410.78
<font color="#EF2929"><b>OpenGL</b></font> shading language version string: 4.60 NVIDIA
<font color="#EF2929"><b>OpenGL</b></font> context flags: (none)
<font color="#EF2929"><b>OpenGL</b></font> profile mask: (none)
<font color="#EF2929"><b>OpenGL</b></font> extensions:
<font color="#EF2929"><b>OpenGL</b></font> ES profile version string: <font color="#EF2929"><b>OpenGL</b></font> ES 3.2 NVIDIA 410.78
<font color="#EF2929"><b>OpenGL</b></font> ES profile shading language version string: <font color="#EF2929"><b>OpenGL</b></font> ES GLSL ES 3.20
<font color="#EF2929"><b>OpenGL</b></font> ES profile extensions:
</pre>

Also `uname -r` returns:
`4.15.0-46-generic`

For the Glava version (`glava --version`) it returns unknown, which could be a problem? Right now it's installed from the apt repository within linuxuprising's ppa (https://www.linuxuprising.com/2018/11/embed-audio-visualizer-on-your-linux.html):
`GLava (glava) unknown (stable, unix/fhs)`

For the audio part, this is the output of `pactl list sources` with music playing. The State of `Source #0` changes from RUNNING to SUSPENDED when I stop the music, sometimes when I stop the music and play again it takes some time and says State: IDLE. `Source #1` turns from SUSPENDED to RUNNING when activating the microphone.

<pre>Source #0
	State: RUNNING
	Name: alsa_output.pci-0000_00_1f.3.analog-stereo.monitor
	Description: Monitor of Built-in Audio Analog Stereo
	Driver: module-alsa-card.c
	Sample Specification: s16le 2ch 44100Hz
	Channel Map: front-left,front-right
	Owner Module: 7
	Mute: no
	Volume: front-left: 8251 /  13% / -54,00 dB,   front-right: 8251 /  13% / -54,00 dB
	        balance 0,00
	Base Volume: 65536 / 100% / 0,00 dB
	Monitor of Sink: alsa_output.pci-0000_00_1f.3.analog-stereo
	Latency: 0 usec, configured 16000 usec
	Flags: DECIBEL_VOLUME LATENCY 
	Properties:
		device.description = &quot;Monitor of Built-in Audio Analog Stereo&quot;
		device.class = &quot;monitor&quot;
		alsa.card = &quot;0&quot;
		alsa.card_name = &quot;HDA Intel PCH&quot;
		alsa.long_card_name = &quot;HDA Intel PCH at 0x94328000 irq 16&quot;
		alsa.driver_name = &quot;snd_hda_intel&quot;
		device.bus_path = &quot;pci-0000:00:1f.3&quot;
		sysfs.path = &quot;/devices/pci0000:00/0000:00:1f.3/sound/card0&quot;
		device.bus = &quot;pci&quot;
		device.vendor.id = &quot;8086&quot;
		device.vendor.name = &quot;Intel Corporation&quot;
		device.product.id = &quot;a170&quot;
		device.product.name = &quot;Sunrise Point-H HD Audio&quot;
		device.form_factor = &quot;internal&quot;
		device.string = &quot;0&quot;
		module-udev-detect.discovered = &quot;1&quot;
		device.icon_name = &quot;audio-card-pci&quot;
	Formats:
		pcm

Source #1
	State: SUSPENDED
	Name: alsa_input.pci-0000_00_1f.3.analog-stereo
	Description: Built-in Audio Analog Stereo
	Driver: module-alsa-card.c
	Sample Specification: s16le 2ch 44100Hz
	Channel Map: front-left,front-right
	Owner Module: 7
	Mute: no
	Volume: front-left: 8251 /  13% / -54,00 dB,   front-right: 8251 /  13% / -54,00 dB
	        balance 0,00
	Base Volume: 5206 /   8% / -66,00 dB
	Monitor of Sink: n/a
	Latency: 0 usec, configured 0 usec
	Flags: HARDWARE HW_MUTE_CTRL HW_VOLUME_CTRL DECIBEL_VOLUME LATENCY 
	Properties:
		alsa.resolution_bits = &quot;16&quot;
		device.api = &quot;alsa&quot;
		device.class = &quot;sound&quot;
		alsa.class = &quot;generic&quot;
		alsa.subclass = &quot;generic-mix&quot;
		alsa.name = &quot;ALC3241 Analog&quot;
		alsa.id = &quot;ALC3241 Analog&quot;
		alsa.subdevice = &quot;0&quot;
		alsa.subdevice_name = &quot;subdevice #0&quot;
		alsa.device = &quot;0&quot;
		alsa.card = &quot;0&quot;
		alsa.card_name = &quot;HDA Intel PCH&quot;
		alsa.long_card_name = &quot;HDA Intel PCH at 0x94328000 irq 16&quot;
		alsa.driver_name = &quot;snd_hda_intel&quot;
		device.bus_path = &quot;pci-0000:00:1f.3&quot;
		sysfs.path = &quot;/devices/pci0000:00/0000:00:1f.3/sound/card0&quot;
		device.bus = &quot;pci&quot;
		device.vendor.id = &quot;8086&quot;
		device.vendor.name = &quot;Intel Corporation&quot;
		device.product.id = &quot;a170&quot;
		device.product.name = &quot;Sunrise Point-H HD Audio&quot;
		device.form_factor = &quot;internal&quot;
		device.string = &quot;front:0&quot;
		device.buffering.buffer_size = &quot;65536&quot;
		device.buffering.fragment_size = &quot;32768&quot;
		device.access_mode = &quot;mmap+timer&quot;
		device.profile.name = &quot;analog-stereo&quot;
		device.profile.description = &quot;Analog Stereo&quot;
		device.description = &quot;Built-in Audio Analog Stereo&quot;
		alsa.mixer_name = &quot;Realtek ALC3241&quot;
		alsa.components = &quot;HDA:10ec0290,103c80a9,00100003 HDA:80862809,80860101,00100000&quot;
		module-udev-detect.discovered = &quot;1&quot;
		device.icon_name = &quot;audio-card-pci&quot;
	Ports:
		analog-input-internal-mic: Internal Microphone (priority: 8900)
		analog-input-mic: Microphone (priority: 8700, not available)
	Active Port: analog-input-internal-mic
	Formats:
		pcm</pre>

After trying `Source #1` and speaking to the microphone I see it working and oscillating according to my voice frequencies, also FPS seem consistent, just as you said. This issue might not be a video problem at all.

![Screenshot from 2019-03-12 00-58-51](https://user-images.githubusercontent.com/4147225/54165900-fafed800-4462-11e9-939c-ddd6191b9e76.png)

`pactl list source-outputs` literally returns nothing on terminal. No idea.

It definitely looks like it can't pick up my audio. Thanks a lot for your help! Let's see what else we can do.

**Comment by wacossusca34** [comment]
Running the `4.6.0 NVIDIA 410.78` driver and having no issues seeing the circle from `radial` rules out any rendering issues. Your microphone working with GLava further narrows it down to a problem with obtaining a monitor for your default output device, as I originally guessed.

Thanks for quickly following through with my requests, this makes fixing these issues much easier.

Also:

> For the Glava version (`glava --version`) it returns unknown, which could be a problem?

It just means whoever built it did so by downloading a source archive instead of cloning it through git. However, you should be able to get the package version via `apt-cache policy glava`.

I also had no idea a PPA even existed for GLava, but it shouldn't pose an issue.

> `pactl list source-outputs` literally returns nothing on terminal. No idea.

I should have clarified running this _while GLava is attempting to monitor system sound_. If it still displays nothing there, then that's probably an error handling issue. Also, you should run GLava with the `--verbose` flag -- it will spit out the name of the device or monitor it is it _reportedly_ listening from.

After doing so, if you see a device in `pactl list source-outputs`, then two things could be happening:

* It's the wrong device, not your default audio device, and for some reason `pa_server_info->default_sink_name` is reporting the wrong device.

* It's the correct device, yet no output can be read from it. This is almost certainly a PulseAudio or driver bug. In this case, I would ask if you are also unable to record system sound with other applications (ie. OBS).

if you don't see a device, then another two things could be happening:

* GLava is failing to obtain a monitor correctly but is not error checking correctly (in which case the error itself might help with the issue as well)

* PulseAudio bugged out somewhere trying to add the source output.

In the meantime I'm going to seriously consider JACK support because I am slowly liking PA less and less.

**Comment by gerardparareda** [comment]
`apt-cache policy glava` did the trick:
<pre>glava:
  Installed: 1.6.0-1~bionic
  Candidate: 1.6.0-1~bionic
  Version table:
 *** 1.6.0-1~bionic 500
        500 http://ppa.launchpad.net/linuxuprising/apps/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
</pre>

Here's the output of `pactl list source-outputs` with glava running and music playing:
<pre>Source Output #0
	Driver: protocol-native.c
	Owner Module: 11
	Client: 12
	Source: 0
	Sample Specification: float32le 2ch 22050Hz
	Channel Map: front-left,front-right
	Format: pcm, format.sample_format = &quot;\&quot;float32le\&quot;&quot;  format.rate = &quot;22050&quot;  format.channels = &quot;2&quot;  format.channel_map = &quot;\&quot;front-left,front-right\&quot;&quot;
	Corked: no
	Mute: no
	Volume: front-left: 65536 / 100% / 0,00 dB,   front-right: 65536 / 100% / 0,00 dB
	        balance 0,00
	Buffer Latency: 3696 usec
	Source Latency: 0 usec
	Resample method: speex-float-1
	Properties:
		media.name = &quot;audio for glava&quot;
		application.name = &quot;glava&quot;
		native-protocol.peer = &quot;UNIX socket client&quot;
		native-protocol.version = &quot;32&quot;
		application.process.id = &quot;6140&quot;
		application.process.user = &quot;gerard&quot;
		application.process.host = &quot;hp&quot;
		application.process.binary = &quot;glava&quot;
		application.language = &quot;C&quot;
		window.x11.display = &quot;:0&quot;
		application.process.machine_id = &quot;88176c2319f346408c5d894887a99b42&quot;
		application.process.session_id = &quot;c2&quot;
		module-stream-restore.id = &quot;source-output-by-application-name:glava&quot;
</pre>

Here's `glava --verbose`:
<pre>Using backend: &apos;glx&apos;
Loading module: &apos;bars&apos;
found GLSL stage: &apos;1.frag&apos;
compiling: &apos;1.frag&apos;
Using audio source: 0
FPS: 61.97, UPS: 60.01
FPS: 60.95, UPS: 60.95
FPS: 59.98, UPS: 59.98
...
</pre>

The `Source #0` appears to be correct in both cases. I just tried recording with OBS and just as you said: I can record my microphone flawlessly but not the output audio, it just doesn't work.

**Comment by gerardparareda** [comment]
I just fixed it running `rm -r ~/.config/pulse; pulseaudio -k`. I have no idea, I guess Pulse Audio had some wrong configuration?

**Comment by wacossusca34** [comment]
> I just tried recording with OBS and just as you said: I can record my microphone flawlessly but not the output audio, it just doesn't work.

Well, that rules out a GLava bug entirely.

> I just fixed it running rm -r ~/.config/pulse; pulseaudio -k. I have no idea, I guess Pulse Audio had some wrong configuration?

Argh! You should have saved the old config to see what was causing it.

Either way, I'm closing this since it's not a GLava bug, but I am interested in what was causing this as it might help with troubleshooting if other users run into the same issue.

**Comment by ashutoshgngwr** [comment]
@gerardparareda I faced the same situation.
@wacossusca34 Lost information incoming!! :fireworks: 

[pulse.zip](https://github.com/wacossusca34/glava/files/3317117/pulse.zip)

**Comment by Anyeos** [comment]
Same "issue" here, solved with activating Loopback device for Pulseaudio (there are a systray app for Gnome Shell to click for enable/disable it).
You can use too pavucontrol to select and change sound devices, sources, sinks and volume.
Don't forget to choose the corresponding for "glava: audio for glava from" -> And choose your desired source of sound.
