### ISSUE TITLE
GLXBadFBConfig

### ISSUE THREAD

**Issue by banancc** [wacossusca34/glava#117]
Hello!
When i try to run glava i got this :

>  qwerty@qwerty:~$ glava
> 
> X Error of failed request:  GLXBadFBConfig
>   Major opcode of failed request:  155 (GLX)
>   Minor opcode of failed request:  34 ()
>   Serial number of failed request:  50
>   Current serial number in output stream:  49

I have installed OpenGL.
Can you please help me?
Thanks.

**Comment by wacossusca34** [comment]
This is almost always due to a driver that doesn't support the requested OpenGL implementation. Unless your `glxinfo` indicates that OpenGL 3.x versions are supported, this issue is rooted in lack of hardware support (see #34). Your options are:

* Use the software rasterizer `llvmpipe` instead, as it works alright with GLava (will need performance tuning to lower system load)
* Install new graphics hardware that isn't ancient.

Closing this issue unless you can indicate this is a rare circumstance of `GLXBadFBConfig` being returned for other reasons. It might be worth setting a handler to print a more concise error message indicating driver support to be an issue, though.
