### ISSUE TITLE
Similar visualizer for windows 10

### ISSUE THREAD

**Issue by cathedrall** [wacossusca34/glava#126]
Hi,

Love your work! Basically, can't live without this when I'm using Linux, but unfortunately I'm sometimes forced to use Windows due to work requirements. 

I've scoured the Internet looking for a similar solution that you have here, and was wondering if anyone (including the author) knew of anything. I've tried "Rainmeter", but none of the Rainmeter visualizers come close to the versatility that you have here with Glava. 

If there isn't a solution (even paid for that matter) have you considered porting to windows? 

Thank you for all of your hard work!

**Comment by wacossusca34** [comment]
I'm open to PRs. Three things need to happen to make support for another OS possible:

* `xwin.c` needs its functionality abstracted by the `wcb_*.c` interface, which is just some minor refactoring
* A sound backend needs to be written for Windows. Not too difficult.
* A windowing backend needs to be written for Windows -- which is difficult and will require some unpleasant code to get the behavior GLava offers on most Linux WMs.

Unfortunately the last point is quite daunting for me since there is a lack of documentation available that I need to implement working transparent desktop windows that are absent from the window list.

The best way to do this would be to use some of Rainmeter's code to implement this, however it has an incompatible license (GPLv2 versus GLava's GPLv3) -- you would need to ask the author(s) permission to use a more recent version of the GPL.

At the moment I am not in particularly good health so I am not interested in implementing this myself. I also do not know of any other decent audio spectrum visualization software on Windows other than Rainmeter.
