### ISSUE TITLE
Latest git build error

### ISSUE THREAD

**Issue by vaskark** [wacossusca34/glava#130]
I tried to build the latest git and received this error:

```
/bin/sh: 1: [[: not found
Makefile:35: *** recipe commences before first target.  Stop.
```

I'm on Ubuntu 19.04.

**Comment by wacossusca34** [comment]
@vaskark fixed in referenced commit. Note that the `Makefile` is just a wrapper for meson to produce functionally equivalent builds to older GLava versions, so you can always use `meson` to configure & build the project.

I'm in the middle of some considerable feature additions so `master` will be moving fairly quickly, although it will remain stable.
