### ISSUE TITLE
Ever thought about maybe implimenting wayland support, as it is quickly being made into the standard?

### ISSUE THREAD

**Issue by Toshimonster** [wacossusca34/glava#27]

**Comment by wacossusca34** [comment]
There's a handful of problems with Wayland support:

- it's impossible to port '"xroot"' style opacity/transparency. The wayland protocols required to implement this are not standardized.

- Getting desktop windows to behave appropriately for Wayland compositors will be a massive pain. `wl_shell_surface` is the only interface that seems to provide some of the interaction I need, and desktop features seem to be something I would have to implement through the compositor itself (ie. as a plugin/extension, if such things are supported by said compositor).

> .. as it is quickly being made into the standard?

"the standard"? Wayland is _far_ from seeing widespread adoption at the moment and Wayland developers have been causing more problems than they solve by leaving important features to the implementation, rather than standardizing them.

The two things I will consider regarding Wayland support are: 

- The ability for GLava to be run as a GNOME shell extension for Wayland sessions.

- The ability to compile and run GLava without any X11 dependencies, thus allowing users to solely use GLFW for window creation. This, however, means I'm limited to whatever GLFW exposes from the underlying windowing system for manipulating GLava's window, which means special window types and hints will completely break under Wayland.

I don't see the latter option as a good use of my time, and will only look into the former option if there is enough demand for it.

**Comment by rhysperry111** [comment]
Wayland has matured quite a bit now with most compositors standardizing on wlroots. 

Is there a chance that your stance has changed?

**Comment by coderobe** [comment]
wlroots doesn't support nvidia graphics, and other wayland libraries behave differently so you still have to special case this for the different implementations.

**Comment by rhysperry111** [comment]
Apparently [glpaper](https://hg.sr.ht/~scoopta/glpaper) can be used to take a glsl shader and render it as a wallpaper. Would this help in any way with moving to wayland?

**Comment by PopeRigby** [comment]
Any new thoughts on this?

**Comment by advaithm** [comment]
With fedora now defaulting to wayland can this issue be reopened.a lot of things are now standard across des/wms

**Comment by PolyMeilex** [comment]
@jarcode-foss Would you be willing to merge a `wlr-layer-shell` support PR if I end up writing one? 
I would love to see something like glava running in my compositor someday, but I don't want to reinvent the wheel.

I don't promise anything yet, I'm not even a `c` programmer, but at first glance it looks like `X11` code is separated quite nicely from the rest of the codebase, and does not leek into the internal API in any way, so I probably just need to expose GL context initialized by `layer-shell` client instead of `X11` one, this sadly means that we can't use GLFW

**Comment by isshin1** [comment]
hey @PolyMeilex  any update about this one ? hopefully one day we will be able to use it in sway

**Comment by PolyMeilex** [comment]
> hey @PolyMeilex  any update about this one ? hopefully one day we will be able to use it in sway

No response from mantainer therefore I'm not working on it, I opted in to reinventing the wheel instead, but it's low on my priorities list so don't expect anything.

**Comment by isshin1** [comment]
Will be awesome if you can just fork it, maintainer havent been active since an year, there are a lots of open issues and pr like this one

**Comment by PolyMeilex** [comment]
> wlroots doesn't support nvidia graphics, and other wayland libraries behave differently so you still have to special case this for the different implementations.

Also wlr prefix means that it's created by wlroots team not that it only works on wlroots, so Nvidia has nothing to do with this, KDE supports it, new Cosmic DE by System76 does, and all wlroots compositors do, and even my toy compositor also not based on wlr does. 

Only unsupported compositor is Gnome (Mutter to be precise but Gnome is the only wayland capable consumer of libmutter) but Gnome developers state that it is not supported by design, so I think it's fine to not support it, it's their choice and should just be respected.

To avoid confusion wlr_layer_shell is even in the process of renaming and moving to wayland-protocols repo. That does not change the fact that Gnome will never implement it or any other protocol that might be similar tho.
