### ISSUE TITLE
Documentation on Gradients?

### ISSUE THREAD

**Issue by Riokei** [wacossusca34/glava#45]
As someone not that up to speed on OpenGL programming and stuff can we get some documentation in the wiki about how to define gradients?

**Comment by wacossusca34** [comment]
At the moment it's not too intuitive, but it's not hard either. You just have to define a `COLOR` macro and use the variable `d` (for 'distance', although it's actualled named `pos` for the `graph` module which should probably be changed).

The following code creates a white-to-black gradient:

```GLSL
#define COLOR vec4(1.0, 1.0, 1.0, 1.0) * (d / 100)
```

The `vec4(...)` syntax is for a _four dimensional vector_, which sounds really generic, but it's what is used to represent most multi-component datatypes. In this case it's just representing a RGBA color in _floating point_ values (from `0.0` to `1.0`). The variable `d` is divided by `100` since `d` is really just the number of pixels from the baseline (or center for `radial`), and we need small values between `0` and `1` to slowly increase the color.

This isn't a real gradient between two colors though, and the `vec4(...)` syntax is unessecary for most. A more complete approach is as follows:

```GLSL
#define COLOR mix(#882222, #2233FF, clamp(d / 100, 0, 1))
```

Here, we use an extension that I have written into GLava itself allowing hexidecimal colors to expand into the `vec4` syntax used in the first example. This means you can specify a hexidecimal color and perform operations on it like a normal vector (if the alpha component is omitted, it is assumed to be `1.0`). The `mix` function performs a weighted average between the first two parameters (effectively making a gradient), and the last argument is the `d / 100` from our previous code to indicate how the gradient is scaled. Finally, the `clamp(..., 0, 1)` is nessecary to make sure weirdness doesn't happen once we reach either ends of the gradient.

I will hold off on adding actual documentation for this since there's some inconsistencies with where and how the `d` (distance) variable is defined.

**Comment by Aaahh** [comment]
I feel like we should make a repository or something to host different setups, kind of like https://www.shadertoy.com/

I ended up using this:
```
#define RCOL_OFF (gl_FragCoord.x / 3000)
/* left color offset */
#define LCOL_OFF ((screen.x - gl_FragCoord.x) / 3000)
/* vertical color step */
#define LSTEP (d / 180)

/* Bar color */
#define COLOR vec4((0.2 + RCOL_OFF) + LSTEP, max(0.3 - LSTEP, 0.0808), (0.25 + LCOL_OFF) - (LSTEP * 1.5), sin((d/500)))

```
It's mostly wacossusca's, 
I was trying to figure out how to change the color of the bar based off d but all I ended up with was changing the color of the top of the bar

**Comment by wacossusca34** [comment]
@Aaahh that approach is admittedly confusing, although it's what I came up with on the spot to have a two-dimensional gradient. A more sane approach would be to add more `mix` calls:

```GLSL
#define GRADIENT_V mix(#882222, #2233FF, clamp(d / 100, 0, 1))
#define GRADIENT_H mix(#000000, #FFFFFF, clamp(gl_FragCoord.x / screen.x, 0, 1))
#define COLOR (GRADIENT_V + GRADIENT_H) / 2
```

This takes a horizontal and vertical gradient and averages them together. `gl_FragCoord.x` is the X position of the fragment being rendered (position of pixel on screen), and `screen.x` is the width of GLava's rendering area. It's a bit cleaner this way, although the color inputs will no longer produce intuitive results due to the averaging.

**Comment by wacossusca34** [comment]
Closing for the time being, due to being a non-issue.
