### ISSUE TITLE
Renderer destruction is absent

### ISSUE THREAD

**Issue by Aaahh** [wacossusca34/glava#47]
I already wrote the code but I need you to finish this function:
https://github.com/wacossusca34/glava/blob/ebade264ea1855afe88421ccc3ec22fc835696dc/render.c#L1629

**Comment by Aaahh** [comment]
So I had two ways how I did this, the first way I would one the same thread destroy and reload on a file change (which using a Linux (or maybe Unix I can’t remember) api that monitors file changes, so no performance problem) and then redraw using a new render (I don’t bother editing what changes, I destroy render and recreate). 

My new method is using pthreads, file change has its own thread, the render has its own thread, and a new render thread is created for the new config. The idea is that I fade in the new render as I fade out the old render, also the advantage is that glava is ways running and no time is lost destroying render (even if it’s quick). 

Also this gives us different layers we could do. It’s pretty non-invaise code wise to top it off.

**Comment by Aaahh** [comment]
The fades I haven’t got yet, but the idea is to either fade the actual render window or fade everything in OpenGL 

Also rather than a linear fade I was thinking exponential

**Comment by wacossusca34** [comment]
Like you mentioned with multiple renderer threads for each configuration, glava's `renderer.c` doesn't really facilitate dynamic configs since it sets up a lot of state based on the config through initialization.

Personally, I'm not completely on-board with GLava's config being updated at runtime simply because existing setups can usually be reloaded with `killall glava && glava`, and code to monitor the filesystem for shader changes could be seen as unnecessary (or an annoyance for editors that auto-save in place).

That being said, proper destruction is needed in GLava and I'm not going to ignore that problem. At the moment, it actually seems to segfault on close randomly!

**Comment by Aaahh** [comment]
Well the idea is that, back to the issue with the screenshots of chill nation, the idea is that the color can be dynamic rather then static or change throughout the day and over time

**Comment by wacossusca34** [comment]
@Aaahh colors can be technically dynamic already. If you want to facilitate inputs to shaders from something outside of the glava process, that is a more feasible feature request and doesn't involve reloading configs (which is actually quite slow).

**Comment by Aaahh** [comment]
Idk man I’m just trying to make this a fancy program, and rather than restarting over and over to change module versus one big module that contains all the other modules

**Comment by wacossusca34** [comment]
If you elaborate on what you are trying to accomplish I can look to adding a feature in glava to help facilitate that if it's within the realm of reason. I'm not going to add features aimlessly, though.

**Comment by wacossusca34** [comment]
Should be much better now. I saved some (minor) allocations from leaking into runtime as well, and GLava no longer has OpenGL termination issues on some drivers.
