### ISSUE TITLE
"desktop" attribute not present on i3-gaps

### ISSUE THREAD

**Issue by Longhinus** [wacossusca34/glava#6]
The desktop attribute is not available on i3-gaps (at least since the last gaps-next version).

If you could add a way to dispaly the visualizer in background instead of over other windows. Because i3 floating window must be ontop of tiling ones. On the official wiki it is say that the desktop attribute (to display a window beneath others) is not implemented in i3, thanks.

**Comment by wacossusca34** [comment]
> On the official wiki it is say that the desktop attribute (to display a window beneath others) is not implemented in i3, thanks.

Unfortunately this is something the window manager itself needs to implement, as GLava itself has no control over where the window is positioned. There are other ways you can try to get GLava embedded in your desktop, however:

- Using `#request setxwintype "dock"` or a similar window type that has unique behaviour under i3.

- Adding `#request addxwinstate <value>` requests, where `<value>` can be `"modal"`, `"sticky"`, `"skip_taskbar"`, `"skip_pager"`, `"above"`, `"below"`,  or `"focused"` (and other unrelated options for embedding). You can use multiple `addxwinstate` lines.

`#request addxwinstate "below"` and using `setxwintype` with a window type that i3 _doesn't_ tile normally (ie. it can just be positioned anywhere) should work. Otherwise, you will need custom rules in your i3 config for GLava.

If you find a combination of `addxwinstate` and `setxwintype` lines gets GLava in your desktop and fixes your issue, please respond with them since I am planning to implement a single option to handle all the WM-specific issues and do this behind the scenes.

**Comment by Longhinus** [comment]
Than for the rep, actually in i3, a non-tiling window must be on top of tiling ones. Which makes it impossible. I think I may find an answer modifying my i3 config.

**Comment by wacossusca34** [comment]
It also seems i3 has an IPC interface: https://i3wm.org/docs/ipc

I can probably use this to get GLava embedded in the desktop of i3 without requiring the user to modify their config, but I will need to research a bit about i3 since I have not used it myself.

If you do find an answer by modifying your config, please post your changes so that other users may see it.

**Comment by pasimko** [comment]
How does conky do it?

**Comment by wacossusca34** [comment]
@pasimko Conky draws to the root X11 window instead of creating its own. GLava creates its own window since it needs to also create its own OpenGL context. There may be some hacky way I can create a GLX context for the root X11 window, but I will have to ditch glfw's window creation code in order to do so.

**Comment by wacossusca34** [comment]
Depending on how the [issue referenced above](https://github.com/Airblader/i3/issues/195) is responded to, I may attempt to implement some workaround trying to create a GLX context on the root window, now that I have separate window creation backends.

**Comment by wacossusca34** [comment]
Update: I tried to implement instantiating a GLX context on the root window. It did not work -- I was able to create the context and use it, but was not able to display anything. The only other application I can find that has attempted something similar is xscreensaver's `-root` option, which also does not work.

The only alternative here is to create an indirect GLX context and _copy the results to the root window_ via traditional X11 drawing, which would be incredibly slow, even with using XShm.

The only practical solution to this issue is for the i3 developers to properly respect desktop windows -- this issue really isn't my responsibility, so I'm closing it.

**Comment by Aaahh** [comment]
I think I recall it being possible through the i3 config, ill look into it later today

**Comment by wacossusca34** [comment]
@Aaahh if you do find a solution via configuring i3, please share it.

**Comment by Aaahh** [comment]
I failed to find it, it was on https://www.reddit.com/r/unixporn/
Anyway, I'm working on setting glava as a child of WID 0 (background window of i3), or background of what is the main DE.

**Comment by wacossusca34** [comment]
This problem may be fixed by using the new `#request setxwintype "!-"`, see the above reference. In short, `'!'` causes the window to bypass the window manager (`override_redirect` / `CWOverrideRedirect`), and `'-'` stacks the window below everything else (`XLowerWindow`).

**Comment by wacossusca34** [comment]
@Longhinus if you could test the results, that would be helpful.

**Comment by xg-teodor** [comment]
Hey @wacossusca34, thanks for your work on this!

I've tested the latest git version with i3 and it works fine with `#request setxwintype "!-"`.

**Comment by wundrweapon** [comment]
I tried this and it works and all, but the xwinstate fullscreen request doesn't work

**Comment by wacossusca34** [comment]
@wundrweapon as @strongeggs mentioned, you will have to position the window yourself. `rc.glsl` explicitly states that `setxwinstate` does not work with unmanaged window types:

```GLSL
/*
   ...
   
   Alternatively, you can set this value to "!", which will cause
   the window to be unmanaged. If this is set, then `addxwinstate`
   will do nothing, but you can use "!+" and "!-" to stack on top
   or below other windows.
*/
```

**Comment by LeelaPakanati** [comment]
I'm trying to run this on i3-gaps but when I set "!-" on as the xwintype, it just doesn't show up anywhere. The program seems to run (I get the fps updates on the terminal) but nothing shows up.
