### ISSUE TITLE
'circle' module fails on Intel Haswell graphics

### ISSUE THREAD

**Issue by wundrweapon** [wacossusca34/glava#70]
I have GLava installed on my Manjaro laptop via the `glava-git` AUR package and on my Void machine by compiling via source. I noticed that GLava will scale with volume, but not always.

On the Manjaro machine, raising/lowering volume via either pavucontrol or the volume keys (which pavucontrol responds to) will not scale audio output. However, using the laptop to play Bluetooth audio from my phone, I can adjust my phone's volume to scale GLava.

On my Void machine, adjusting volume via pavucontrol will always scale GLava.

~~While I'm here, did you ever consider my right/left split on the sides of the monitor idea?~~

**Comment by wundrweapon** [comment]
Ah, and something I forgot to note - the Void machine can handle the Circle module just fine, whereas the Manjaro laptop just covers the screen with a gray overlay (will upload a screenshot when I can, if requested). Interestingly, both are using the same settings, including desktop mode w/ clickthrough and the above and fullscreen EWHM states, as well as using native opacity. Genuinely no idea why this one module is the only touble-maker.

**Comment by wacossusca34** [comment]
GLava listens to a monitor of your default PulseAudio output device, so any source feeding that device should reflect volume changes in the visualizer. It's possible to exhibit this behavior with some strange pulseaudio configurations with extra sound sinks, though.

I can look into this later today.

**Comment by wacossusca34** [comment]
> the Manjaro laptop just covers the screen with a gray overlay (will upload a screenshot when I can, if requested).

This sounds like a graphics or compositing issue. Please post the output of `glxinfo` on that machine, and try using `"xroot"` or `"none"` transparency to see if that fixes it.

**Comment by wundrweapon** [comment]
Neither xroot nor none fixed the issue. `glxinfo` can be found [here](https://hastebin.com/xowotadeti.py)

**Comment by wacossusca34** [comment]
@wundrweapon Does the issue occur on `v1.5.6` (or older) versions? I [made a change recently to `master`](https://github.com/wacossusca34/glava/commit/3da1fb34dd931568e224c95a8272c113bb463d98) that effects how fragment coords are handled in the `radial` module. I can test the output on `llvmpipe` (mesa), but I'm not sure if that's a suitable environment to try to reproduce the issue you have with intel graphics (which I don't have available to test).

Unfortunately vendor-specific GLSL bugs are really annoying to debug.

As for the audio issue, I'm going to need to see how you have pulseaudio configured on the problematic system. It sounds like you may have some strange setup with null sinks, and I'm fairly sure GLava has little to do with it.

**Comment by wundrweapon** [comment]
I just tested this, and the issue is giving consistent results on both 1.5.1 and 1.5.6  
~~Apparently the AUR git package is very good at *not* updating when I tell it to...~~

**Comment by wacossusca34** [comment]
@wundrweapon have you tried `master`? `1.5.1` and `1.5.6` are both tagged before the mentioned change, so you'll want to pull from `master` instead.

**Comment by coderobe** [comment]
`1.5.6` is also the current version in [[community]](https://www.archlinux.org/packages/community/x86_64/glava/) of the arch repos, saves you a rebuild and cuts out build issues from the mix.

**Comment by wacossusca34** [comment]
@wundrweapon can you please report if you get the issue on `master`?

**Comment by wundrweapon** [comment]
Sorry, got caught up in a hellstorm of work. The problem persists, though oddly enough the `#request addxwinstate "above"` command no longer does anything. I highly doubt GLava is at fault here, so I'll keep digging before filing an official bug report

P.S. the radial module never had any issues, circle is the one at fault

**Comment by wacossusca34** [comment]
> though oddly enough the `#request addxwinstate "above"` command no longer does anything

@wundrweapon "no longer"? If it was working before, perhaps it was with a different window type? Keep in mind that window hints/state will not work with unmanaged windows. Using the `--desktop` flag will also override `addxwinstate` options defined in `rc.glsl`.

I am primarily concerned about the graphical issue with `circle` on your device with `"Intel(R) Haswell Mobile"` graphics. Unfortunately I cannot reproduce this due to only having an AMD and Nvidia card to test with, and @coderobe reported that the issue is not observable on his system with Intel graphics. I strongly suggest you to ensure both Xorg and your drivers are up to date.

If you are still encountering the graphical issue on `master`, I have to assume it is because of something going wrong when passing the contents of one shader pass to another with >2 passes. `circle/2.frag` uses a bunch of `texelFetch` calls to blend/alias the output from the first pass, and `circle/3.frag` will pre-multiply the color channels with the alpha channel if `"native"` transparency is being used (due to this being required by Xorg). In this case, I have to ask you to try:

- Disabling `"native"` transparency and using `"xroot"` or just a solid (contrasting) background color.
- **Or** removing `circle`'s aliasing pass by running `cd /etx/xdg/glava/circle && sudo mv 2.frag 2.frag.old && sudo mv 3.frag 2.frag`. This will make the output look a lot worse, but may fix the problem.

If either of those solutions fixes the problem for you, I can dig around to see if I'm doing something wrong with shader passes, although I would be inclined to believe this is a driver bug due to it working on nearly all other devices (hardware and software), including those from the same vendor.

I apologize for the verbose response, but these kinds of problems are something I have to get you to debug yourself, unless I can get my hands on the same chip.

**Comment by wacossusca34** [comment]
> Correct. It was working just over a week ago. I was always using the desktop window type, above and fullscreen defined with addxwinstate and setclickthrough true (regardless of those three's lack of effect in desktop windows.

Try taking off the fullscreen hint; desktop windows are typically not fullscreen.

> Tried both, nothing changed.

That is incredibly strange. If `radial` still works, but `circle` doesn't, then I have no idea as to what would cause that (considering both are written very similarly). The only things I can suggest are:

* Ensuring that you are running GLava from a clean configuration. An easy way to do this is to just run `make INSTALL=standalone` and `./glava` to use the `shaders` directory directly from the repository root.

* Changing the first line in `circle/1.frag` from this:
  ```GLSL
  layout(pixel_center_integer) in vec4 gl_FragCoord;
  ```
  to this:
  ```GLSL
  in vec4 gl_FragCoord;
  ```

If neither of those suggestions work, trying doing both (modifying `shaders/circle/1.frag` and running the standalone build).

**Comment by wundrweapon** [comment]
>Try taking off the fullscreen hint

Huh. That did it. No idea why that was working before, then... guess I'll just find a new way to fullscreen it.

>The only things I can suggest

Tried both individually, then both in combination. [Assuming I did everything right](https://pastebin.com/twhzNghF), no dice any way

**Comment by wacossusca34** [comment]
> guess I'll just find a new way to fullscreen it.

Just position it over your entire screen with `setgeometry`.

> No idea why that was working before,

It's probably the odd combination of settings that confused your particular window manager:

* Desktop windows usually are implemented so that they have their own stacking space below all other windows, which can cause the `above` and `below` hints to be interpreted in weird ways:
  * Either it applies strictly to the stacking order of desktop windows (always below regular clients), or
  * Or it applies strictly to the stacking order of normal windows, such that `below` is above desktop features, but below normal clients, and `above` is above normal clients, but below splash windows, etc. (most common)
  * Or it doesn't work at all
* Fullscreen windows also screw with stacking order since they are generally on top of all other clients when they are focused.

The result ends up being an implementation detail. The specification isn't much help here either, as it doesn't indicate stacking order _priority_ when multiple atoms that change said ordering are set.

> Tried both individually, then both in combination. Assuming I did everything right, no dice any way

I honestly cannot think of anything else in the shaders for `circle` that could cause this. I also have no way of reproducing the issue.

I'll keep this issue open and will suggest other possible changes if I come across anything. This might ultimately require someone with the affected hardware debugging the problem themselves.

**Comment by ThibaultLemaire** [comment]
![screencast of circle mod going greyscreen with intel graphics](https://ipfs.io/ipfs/QmVN6Pojgy85E2FUZ1C8HkXaPvgqUAEdDYPvb4Ac4xKrGP/Screencast%20from%2012-11-18%2023:26:08.webm)

**Comment by ThibaultLemaire** [comment]
I'll have a look.

**Comment by ThibaultLemaire** [comment]
I can confirm the whole screen is set to the `OUTLINE` color (I've changed it to `#ff00ff` (bright pink) to test it)

**Comment by ThibaultLemaire** [comment]
I fixed it. Apparently it's an issue with the initialization of the fragment.

``` diff
    else         v = smooth_f(audio_r);
    v *= AMPLIFY;      
    #undef smooth_f
    return v;
}

void main() {
+   fragment = #00000000;
    float
        dx = gl_FragCoord.x - (screen.x / 2),
        dy = gl_FragCoord.y - (screen.y / 2);
    float theta = atan(dy, dx);
    float d = sqrt((dx * dx) + (dy * dy));
    float adv = (1.0F / d) * (C_LINE * 0.5);
```

I guess this is one of those typical undefined behaviour edge-cases. "What happens to an uninitialized vec4?"

**Comment by wacossusca34** [comment]
@ThibaultLemaire Thanks for debugging that. I checked the GLSL specification just to be sure this was undefined behavior as well, so it's an error on my end.

I am still curious as to why _only_ `Intel(R) Haswell Mobile` demonstrated the issue, perhaps the driver is better about setting up execution unit registers on other chips?

**Comment by wundrweapon** [comment]
Tried @ThibaultLemaire's fix and it worked. I'm not much for OpenGL and C, so I couldn't explain this even if I wanted to.

**Comment by wacossusca34** [comment]
This problem is fixed in `master` now.

@wundrweapon it's textbook case of an uninitialized variable. Safe(r) languages either have default initializers or compile-time errors/warnings if the variable isn't guaranteed to be written.

I'm not actually sure if this is technically valid behavior for GLSL; global and local variables are not initialized with default values, but uniforms are. Output (`out`) variables are a little wonky here, they are well-defined for tessellation control shaders, but fragment shaders don't get much here.

This should actually cause graphics artifacts on all Intel HD chips if the driver (or microcode?) does not re-initialize registers, so perhaps this really is a bigger issue.

**Comment by ThibaultLemaire** [comment]
```
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
```

We should be able to find Intel's source code on this. Maybe there's a bug in their implementation and we should let them know? Or maybe other vendors have just been more defensive but it's not required ?

**Comment by banancc** [comment]
> ```diff
>     else         v = smooth_f(audio_r);
>     v *= AMPLIFY;      
>     #undef smooth_f
>     return v;
> }
> 
> void main() {
> +   fragment = #00000000;
>     float
>         dx = gl_FragCoord.x - (screen.x / 2),
>         dy = gl_FragCoord.y - (screen.y / 2);
>     float theta = atan(dy, dx);
>     float d = sqrt((dx * dx) + (dy * dy));
>     float adv = (1.0F / d) * (C_LINE * 0.5);
> ```

where i need to place that script?

**Comment by wacossusca34** [comment]
@banancc this is fixed in `master`, note the referenced commit and the fact that the issue is closed.
