### ISSUE TITLE
Add fifo support

### ISSUE THREAD

**Issue by Scrumplex** [wacossusca34/glava#78]
I would love to use glava, but I don't want it to use a pulse source. I would like to only use mpd's output. The best way would be to support fifo, so glava can display a consistent visualizer that is independent from volume.

**Comment by wacossusca34** [comment]
Will do. This is fairly straightforward as everything needed for a fifo backend already exists, I just need to update it to respect some requests and have a flag to enable it.

**Comment by wacossusca34** [comment]
@wundrweapon Adding a fifo backend will not change any existing behavior. As a common rule I try to keep anything that has any reason to be configurable available as a request in `rc.glsl` (or its respective file).

**Comment by wacossusca34** [comment]
@Scrumplex Support has been added to `master`. See the addition to `README.md`:

> ## Reading from MPD's FIFO output
> 
> Add the following to your `~/.config/mpd.conf`:
> 
> ```
> audio_output {
>     type                    "fifo"
>     name                    "glava_fifo"
>     path                    "/tmp/mpd.fifo"
>     format                  "22050:16:2"
> }
> ```
> 
> Note the `22050` sample rate -- this is the reccommended setting for GLava. Restart MPD (if nessecary) and start GLava with `glava --audio=fifo`.

Fun fact - the old code in `fifo.c` was legacy garbage from an _old_ snapshot of cava that I had planned to incorporate long ago. The [revision to this code in cava](https://github.com/karlstav/cava/blob/master/input/fifo.c) somehow remains to be bugged due to how it handles non-existing input.

I tested my changes a fair amount and was only able to encounter a single bug: for some strange reason starting and stopping the track under MPD incurred a small penalty in latency from the output. Restarting, changing position, choosing a different track all revert the issue and restore normal latency.

I suspect that is an MPD bug since it's visible from the FIFO output itself, not just GLava.

Anyway, @Scrumplex if you could report that this works for you then I can close this issue and tag a new version.

**Comment by Scrumplex** [comment]
It works perfectly! Thank you!

**Comment by Scrumplex** [comment]
The only thing I would like to see is a way to change the fifo path. I usually set it to `~/.mpd/fifo` in mpd.

**Comment by wacossusca34** [comment]
@Scrumplex use `#request setsource <path>` in `rc.glsl` for that. Alternatively, you can change the request using the `-r"setsource <path>"` parameter.

Closing due to being resolved.

**Comment by Scrumplex** [comment]
Thank you again. This was the fastest implementation of one of my feature requests! Never saw someone react to and implement a feature request so fast.

**Comment by wacossusca34** [comment]
@Scrumplex I'm just bored. Make more feature requests.

**Comment by wundrweapon** [comment]
>Make more feature requests
There's still that one I mentioned last month; should I file an official "issue" for it?
