### ISSUE TITLE
How to modify frequency range of visualizers?

### ISSUE THREAD

**Issue by GingkathFox** [wacossusca34/glava#87]
Sorry if this is a stupid question, but how do i change the frequency range of the visualizers? i tried looking in the `.glsl` files, but didnt see anything.

**Comment by wacossusca34** [comment]
If you mean amplitude, you want `AMPLIFY` in most modules except for `graph.glsl`, which uses `VSCALE`.

If you mean the frequency response _axis_ (FFT output), this is handled in the smoothing step. All the parameters for this are in `smooth_parameters.glsl`. Of note, you want `SAMPLE_SCALE`, `SAMPLE_RANGE` defines (see comments for details) and and the `setfftcutoff` request (not recommended to change). Keep in mind the horizontal axis is not represented linearly due to how we perceive pitch.

If for some reason you would like linear frequency plotting, please mention so. Otherwise, I assume this question is answered.

**Comment by GingkathFox** [comment]
Oh sweet, thanks! i didnt think of looking in there.
