### ISSUE TITLE
[Ubuntu 18.04 LTS] `Circle` visualizer displays grey screen

### ISSUE THREAD

**Issue by GingkathFox** [wacossusca34/glava#89]
Its basically all in the title. I tried verbose output, no errors there. Any reason why circle doesnt work but every other visualizer works?

**Comment by coderobe** [comment]
What GPU is this happening on? Sounds like https://github.com/wacossusca34/glava/issues/70

**Comment by coderobe** [comment]
have you tried with git `master` HEAD?

**Comment by GingkathFox** [comment]
HEAD? never seen that.

**Comment by wundrweapon** [comment]
If you're not willing to build from source off the latest commit (which would be `master` HEAD), then try [this solution](https://github.com/wacossusca34/glava/issues/70#issuecomment-438238318) from the aforementioned #70

**Comment by GingkathFox** [comment]
ill prolly do your fix, i dont feel like backing up config files >w<
thanks!

**Comment by wacossusca34** [comment]
@GingkathFox you do not need to re-copy configurations when updating GLava. The shader modules themselves are installed in `/etc/xdg/glava` and _symlinked_ to your user configuration directory, meaning your changes will simply use the updated modules after installing a new version.

Simply update your local repository or clone it from `master` and build/install a new version. Due to the nature of the issue this is almost certainly a duplicate of #70, so I'm closing this.
