### ISSUE TITLE
Glava does not detect microphone?

### ISSUE THREAD

**Issue by dmbomer** [wacossusca34/glava#90]
Glava is installed and functioning 

glava --desktop 
VLC audio and video are detect by glava. 
I notice my microphone is not detected by glava.

I scanned through the rc.glsl file and found reference to audio output source but no audio input source
/* PulseAudio source. Can be a number or a name of an audio
   sink or device to record from. Set to "auto" to use the
   default output device. */
#request setsource "auto"

Is it possible to use glava with microphones?

**Comment by wacossusca34** [comment]
Yes, this is possible. The easiest way is to use the device index, as listed by `pacmd list-sources | grep -E 'index|name:'`. You can also use the device name (eg. `alsa_input.hw_microphone_0` on my system, yours will most likely differ).

By default GLava uses a _monitor_ of your default output device. This means any sound you hear from your speakers/headphones will be what GLava displays (barring some niche configurations).

I will close this since I assume this should answer your question, but if you would like to request a feature (like detecting the default input device with a flag), then please mention so.

**Comment by dmbomer** [comment]
It works.  

Yes I would like to request a feature that detects both but allows you to switch back and forth.  Also do you have any plans on creating a gui for this program?

Thank you Sir

**Comment by wacossusca34** [comment]
@dmbomer changing most settings at runtime is generally not supported. A GUI wrapper is certainly possible, specifically as a separate process so there is no memory overhead for running GLava itself.

I will keep in mind detecting the default input device when I re-write the PulseAudio backend. The holidays are a bit packed for me right now, though.

**Comment by dmbomer** [comment]
Thank you Sir and have a merry Christmas!

**Comment by 4D42** [comment]
Hello, thank you for the solution. It took me a really long time to find this post.

Maybe it would be nice to add this line 

> Yes, this is possible. The easiest way is to use the device index, as listed by `pacmd list-sources | grep -E 'index|name:'`.

in the readme or in the rc.glsl file at the Audio source section?

**Comment by Alex4nder001** [comment]
I have a slightly different problem. If I start glava with #request setsource "auto" and with a headset connected to my PC, it uses microphone input, when I want it to play audio from applications instead. I can set the source to my PC speakers (alsa_output.pci-0000_00_1b.0.analog-stereo.monitor), but it only works if I'm listening through my speakers. When I switch the audio output to my headset, there is no audio visualization. Is it possible to make it work with both my speakers and my headset, regardless which one I'm using, but never to use mic input?
