### ISSUE TITLE
GIT SUBMODULE

### ISSUE THREAD

**Issue by saulocastelo** [wacossusca34/glava#99]
git submodule init  and git submodule update is missing from README.md

**Comment by coderobe** [comment]
That's not required to build glava

**Comment by wacossusca34** [comment]
For anyone that needs clarification, the `glad` submodule is a tool for generating OpenGL headers. Since these headers are already provided in the root repository, there is no need to bother with the submodule unless the included headers need to be re-generated.

It simply exists with a `make` rule to easily allow maintainers to change version and/or what extensions are included in the headers if future additions to GLava require it.
